<?php
/**
 * Created by PhpStorm.
 * User: silvio
 * Date: 20.12.2016.
 * Time: 19:21
 */

namespace AppBundle\Model\Parser;

use AppBundle\Model\Filter\FilterPairHolder;
use AppBundle\Model\ValueHolder\IValueHolder;

abstract class Parser
{
    /**
     * @var FilterPairHolder Holds available filters and their operators.
     */
    protected $filterPairHolder;

    public function __construct(FilterPairHolder $filterPairHolder)
    {
        $this->filterPairHolder = $filterPairHolder;
    }

    /**
     * Takes query generated from frontend and validates/generates values.
     *
     * Validates given query and brings it together into collection of values with corresponding filter and operator.
     *
     * @param string $query string Query generated by querybuilder frontend plugin.
     *
     * @return IValueHolder Value holder.
     */
    abstract public function parseQuery($query);
}
