<?php
/**
 * Created by PhpStorm.
 * User: silvio
 * Date: 20.12.2016.
 * Time: 19:21
 */

namespace AppBundle\Model\Parser;

use AppBundle\Model\Filter\Filter;
use AppBundle\Model\Filter\FilterPairHolder;
use AppBundle\Model\Filter\Type\BooleanFilterType;
use AppBundle\Model\Filter\Type\DoubleFilterType;
use AppBundle\Model\Filter\Type\FilterType;
use AppBundle\Model\Filter\Type\IntegerFilterType;
use AppBundle\Model\Filter\Type\StringFilterType;
use AppBundle\Model\Operator\IsNotNullOperator;
use AppBundle\Model\Operator\IsNullOperator;
use AppBundle\Model\Operator\Operator;
use AppBundle\Model\ValueHolder\IValueHolder;

abstract class Parser
{
    /**
     * @var FilterPairHolder Holds available filters and their operators.
     */
    protected $filterPairHolder;

    public function __construct(FilterPairHolder $filterPairHolder)
    {
        $this->filterPairHolder = $filterPairHolder;
    }

    /**
     * Takes query generated from frontend and validates/generates values.
     *
     * Validates given query and brings it together into collection of values with corresponding filter and operator.
     *
     * @param string $query string Query generated by querybuilder frontend plugin.
     *
     * @return IValueHolder Value holder.
     */
    abstract public function parseQuery($query);

    protected function validateValue(Filter $filter, Operator $operator, $value)
    {
        $operatorClass = get_class($operator);

        if ($operatorClass !== IsNullOperator::class && $operatorClass !== IsNotNullOperator::class) {
            $this->validateValueByFilterType($filter->getType(), $value);
            $this->validateValueByValidators($filter, $value);
        }
    }

    protected function validateValueByFilterType(FilterType $filterType, $value)
    {
        if (!$filterType->validateValue($value)) {
            throw new \InvalidArgumentException("FilterType [${filterType}] validation failed for value ${value}."); //Custom exception?
        }
    }

    protected function validateValueByValidators(Filter $filter, $value)
    {
        foreach ($filter->getValidators() as $validator) {
            if (!$validator->validate($value)) {
                throw new \InvalidArgumentException(); //Custom exception?
            }
        }
    }

    protected function matchValueToFilterType($value, FilterType $filterType)
    {
        $cast = function ($val) use ($filterType) {
            switch (get_class($filterType)) {
                case DoubleFilterType::class:
                    return (double)$val;
                case IntegerFilterType::class:
                    return (int)$val;
                case StringFilterType::class:
                    return (string)$val;
                case BooleanFilterType::class:
                    $strVal = strtolower((string)$val);

                    return (in_array($strVal, array("true", "1", "yes"), true));
                default:
                    throw new \InvalidArgumentException("Unsupported filter type ${filterType}.");
            }
        };

        if (is_array($value)) {
            return array_map($cast, $value);
        } else {
            return $cast($value);
        }
    }
}
